### ISSUE TITLE
XMR transaction completed, while woocommerce order status stays "On-hold"

### ISSUE THREAD

**Issue by tlaurion** [nomiddleman/nomiddleman-woocommerce#2]
Hello @rgostic @nomiddleman @dArkjON @dpobis.

Gave nomiddleman a try but it doesn't currently fulfill its promises for XMR:
> Tired of waking up to a bunch of Pending Payment orders? With automatic order processing every time a customer makes a valid cryptocurrency transaction we will update the order to Paid!

First tried a buy a 2$ test item on my woocommerce, with nomiddleman linked to my XMR wallet on binance, to realize binance requires a transaction ID (deprecated) that nomiddleman doesn't provide. Lost the fund.

Then created two Monero wallets, withdrew all coins from binance into the first, then setuped nomiddleman to point to the wallet address of the second.

Rebought test item on my e-commerce test website, copied (verified) wallet address given of the second address by nomiddleman on order confirmation details, put it in my first wallet to transfer the correct amount to the second. Verified that amount corresponds.

Coins are now received on the second wallet, while woocommerce still shows "On-Hold".

How is the transaction supposed to be validated by the plugin? Is it supposed to work and tested with latest wordpress and woocommerce? Thanks

**Comment by rgostic** [comment]
For monero you currently have to manually reconcile orders as there is no way to automatically process them without you entering your private view key.

We plan to add a private view key option in the future for people that need automated order processing.

For reference - classic mode does not automatically process any orders, autopay mode processes orders but some can slip by, and privacy mode has near 100% order processing.

Best,
Ryan

On Jul 7, 2019, at 5:07 PM, tlaurion <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello.

Gave nomiddleman a try but it doesn't work.
First tried a test buy of 2$ to my XMR account on binance to realize binance requires a transaction ID.

Then created two Monro wallets, transferred all coins into the first, and setuped nomiddleman to point to the wallet address of the second.

Bought item on my e-commerce test website, copied (verified) wallet address of the second address given by nomiddleman on order details, put it in my fist wallet to transfer the amount to the second. Coins are now received on the second wallet, while woocommerce still shows "On-Hold".

How is the transaction validated by the plugin? Is it supposed to work?

**Comment by nomiddleman** [comment]
For monero you currently have to manually reconcile orders.

We plan to add a private view key option in the future for people that need automated order processing.

For reference - classic mode does not automatically process any orders, autopay mode processes orders but some can slip by, and privacy mode has near 100% order processing.

**Comment by tlaurion** [comment]
@nomiddleman @rgostic now I understand.

1. Any possibility to add transaction ID to that the funds can be deposited in exhanges meanwhile (so that sellers receive confirmation of received funds.)
1. Any more detailed documentation available on modes? (autopay, classic, privacy)
1. Any timeline in implementing the private view key option in XMR?

**Comment by nomiddleman** [comment]
1. This opens up the customer forgetting to add the additional piece (memo, destination tag, txID) and the funds being lost.
2. The original website had more detailed docs, we will work on porting them to the new site or github.
3. No timeline right now.

**Comment by tlaurion** [comment]
@nomiddleman 
>     2. The original website had more detailed docs, we will work on porting them to the new site or github.
What was the old website? I'll look it up using archive.to and archive.org.

Thanks

**Comment by rgostic** [comment]
I don't think it has been archived yet. I added some information to the readme.

**Comment by tlaurion** [comment]
Thanks! For reference: https://github.com/nomiddleman/nomiddleman-woocommerce/commit/5f618ef93f192223f87c4d9f6365d6c8c7962ea3
