### ISSUE TITLE
Error - NMM_Util.php

### ISSUE THREAD

**Issue by pablo-hp** [nomiddleman/nomiddleman-woocommerce#39]
After installing the plugin and trying to activate, the following error message appears.

Fatal error: Array and string offset access syntax with curly braces is no longer supported in /home/megamerc/public_html/wp-content/plugins/nomiddleman-crypto-payments-for-woocommerce/src/NMM_Util.php on line 54

WordPress 6.1.1
WooCommercer 7.4.0

**Comment by Nou4r** [comment]
+1 the best plugin to accept crypto payments is no longer working.

**Comment by zellpress** [comment]
The author passed in 2022. I hope someone picks this up.
