### ISSUE TITLE
BTC stealth mode suggests HD Wallet usage

### ISSUE THREAD

**Issue by tlaurion** [nomiddleman/nomiddleman-woocommerce#5]
Wanted to know if providing Electrum MPK in stealth mode with a legacy seed was known to be problematic?

Thanks

**Comment by tlaurion** [comment]
@nomiddleman?

**Comment by nomiddleman** [comment]
No problems at all.

This is key, if you control the private key to your xpub then you will be able to recover any funds sent to addresses generated via the xpub.

As far as setting it up in the plugin:
1. After you enter you xpub the settings screen will update the "Sample Addresses" and display the first three addresses.
2. Make sure these addresses are the same addresses you control in Electrum or any other HD Wallet (If you can't find the first address generated anywhere, do not save the MPK as it is then live.) 
3. If only the 1st address shows in your wallet, we recommend sending a minimum amount to the 2nd or 3rd address and make sure your wallet supports it.
