### ISSUE TITLE
BTC stealth mode lacks proper validation instructions

### ISSUE THREAD

**Issue by tlaurion** [nomiddleman/nomiddleman-woocommerce#6]
After entering Electrum's MPK, 3 addresses are generated with a big fat warning:
> PLEASE VERIFY YOU OWN THESE ADDRESSES BEFORE SAVING OR ELSE LOSS OF FUNDS WILL OCCUR!!!!

I would love to verify. How?

**Comment by nomiddleman** [comment]
A visual character-by-character confirmation, see Issue #5 .
